---
title: "Chart Toppers - Data Description"
author: "Discove-R-Weekly"
date: "10/15/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, cache.lazy = FALSE )
```

## What the ARIA charts and Hottest 100 say about Australia's changing music tastes.

Our team aims to investigate how Australian music tastes have changed over time by comparing the audio features of tracks from the yearly ARIA and Triple-J hottest 100 charts from 1970-2019. We will be using the Spotify API to map the tracks from the charts to its corresponding Spotify URI, allowing us to analyse individual tracks against key attributes: duration, key, mode, time signature, acousticness, speechiness, danceability, energy, loudness, valence/happiness and tempo. 

The documentation for the endpoint we are using to get the analysis data is available [here](https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-features/).
We are sourcing the ARIA charts and Triple J Hottest 100 rankings from these sites: 

- https://www.aria.com.au/charts/2019/singles-chart
- https://en.wikipedia.org/wiki/Triple_J_Hottest_100

## Data Sourcing

The data was sourced through calling the above endpoint of the Spotify API. This was done by using their Javascript client libraries since it was what we were most familiar with. 

The source code for pulling data from Spotify is available on Github [here](https://github.com/kvithana/spotify-audio-features-to-csv).

We created or sourced a Spotify playlists which included the songs for each year's charts from 1970 - 2019. This playlist could then be passed to the CLI tool.

Given a list of playlist URIs or URLs in a `.txt` file, the program will get the tracks associated with that playlist, and call the [Spotify Audio Features](https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-features/) endpoint to get insightful information about the tracks.

This data was outputted in csv format into the following structure:

- `playlists.csv` : a lookup of the playlist URI and the playlist name and description
- `/features`: folder with an individual csv for each playlist, containing the audio features data.
- `/tracks`: folder with an individual csv for each playlist, containing data about each track.

The audio features returned from the [Spotify Audio Features](https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-features/) endpoint are quite rich and provide interesting insights over various attributes. The ones we are interested in are:

- `acousticness`: A confidence measure of whether the track is acoustic.
- `danceability` : Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity.
- `energy`: Energy represents a perceptual measure of intensity and activity. 
- `instrumentalness`: Predicts whether a track contains no vocals. “Ooh” and “aah” sounds are treated as instrumental in this context.
- `liveness`: Detects the presence of an audience in the recording.
- `loudness`: The overall loudness of a track in decibels (dB).
- `speechiness`: Speechiness detects the presence of spoken words in a track. 
- `valence`: A measure describing the musical positiveness conveyed by a track. 
- `tempo`: The overall estimated tempo of a track in beats per minute (BPM). 

## Data Cleaning & Consolidation

After the above process of extracting data from the Spotify API, we had to get the data into R and create our dataframes. Since the data coming from the Spotify API is reliable and clean, most of the work involves merging together the data from the CSVs separated by individual playlist into a single dataframe.

We consolidated all the individual playlist CSVs using R (full explanation available in other PDF). We also created additional flag variables to determine whether a playlist came the Hottest 100 `H100` or from the ARIA charts `ARIA` and extracted which charting year the playlist referred as a number.

These consolidated three tibbles were then exported out as our cleaned dataset. The three CSVs are for:

- `features.csv` : contains the audio features for each track
- `tracks.csv` : contains additional identifiable information for each track
- `playlists.csv` : information regarding the playlist itself (name, description, url)
```